name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main

  lint:
    uses: ./.github/workflows/lint.yml

  run-playwright-tests:
    uses: ./.github/workflows/playwright.yml

  prettier:
    uses: ./.github/workflows/prettier.yml

  vitest:
    uses: ./.github/workflows/vitest.yml
